#!/usr/bin/env python3
"""
Build seed.sql for the buena-erp D1 database from partner-files/stammdaten/.
One property (LIE-001) for the demo. Run:

    uv run python workers/ingest/sql/build_seed.py

Then apply with:

    cd workers/ingest && wrangler d1 execute buena-erp --remote --file=sql/seed.sql
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
STAMM = REPO / "partner-files" / "stammdaten" / "stammdaten"
OUT = Path(__file__).resolve().parent / "seed.sql"
PROPERTY_ID = "LIE-001"


def esc(v) -> str:
    if v is None:
        return "NULL"
    s = str(v)
    if s.strip() == "":
        return "NULL"
    return "'" + s.replace("'", "''") + "'"


def num(v) -> str:
    if v is None:
        return "NULL"
    s = str(v).strip()
    if not s:
        return "NULL"
    try:
        f = float(s)
        if f.is_integer():
            return str(int(f))
        return repr(f)
    except ValueError:
        return "NULL"


def boolint(v) -> str:
    s = str(v or "").strip().lower()
    return "1" if s in ("true", "1", "yes", "ja") else "0"


def read_csv(path: Path) -> list[dict]:
    with path.open(encoding="utf-8") as f:
        return list(csv.DictReader(f))


def main() -> None:
    stamm = json.loads((STAMM / "stammdaten.json").read_text(encoding="utf-8"))
    prop = stamm["liegenschaft"]
    buildings = stamm["gebaeude"]
    eigentuemer = read_csv(STAMM / "eigentuemer.csv")
    einheiten = read_csv(STAMM / "einheiten.csv")
    mieter = read_csv(STAMM / "mieter.csv")
    dienstleister = read_csv(STAMM / "dienstleister.csv")

    lines: list[str] = []
    push = lines.append

    push("-- AUTO-GENERATED BY workers/ingest/sql/build_seed.py")
    push("-- Source: partner-files/stammdaten/stammdaten/")
    push(f"-- Property: {PROPERTY_ID}")
    push("")
    push("DELETE FROM owner_units;")
    push("DELETE FROM tenants;")
    push("DELETE FROM service_providers;")
    push("DELETE FROM owners;")
    push("DELETE FROM units;")
    push("DELETE FROM buildings;")
    push("DELETE FROM properties;")
    push("")

    # properties
    push(
        "INSERT INTO properties (id, name, strasse, plz, ort, land, baujahr, sanierung, verwalter, weg_bankkonto_iban, weg_bankkonto_bank, ruecklage_iban) VALUES ("
        + ", ".join(
            [
                esc(PROPERTY_ID),
                esc(prop.get("name")),
                esc(prop.get("strasse")),
                esc(prop.get("plz")),
                esc(prop.get("ort")),
                esc(prop.get("land", "DE")),
                num(prop.get("baujahr")),
                num(prop.get("sanierung")),
                esc(prop.get("verwalter")),
                esc(prop.get("weg_bankkonto_iban")),
                esc(prop.get("weg_bankkonto_bank")),
                esc(prop.get("ruecklage_iban")),
            ]
        )
        + ");"
    )
    push("")

    # buildings
    for b in buildings:
        push(
            "INSERT INTO buildings (id, property_id, hausnr, einheiten, etagen, fahrstuhl, baujahr) VALUES ("
            + ", ".join(
                [
                    esc(b["id"]),
                    esc(PROPERTY_ID),
                    esc(b.get("hausnr")),
                    num(b.get("einheiten")),
                    num(b.get("etagen")),
                    "1" if b.get("fahrstuhl") else "0",
                    num(b.get("baujahr")),
                ]
            )
            + ");"
        )
    push("")

    # units
    for u in einheiten:
        push(
            "INSERT INTO units (id, haus_id, einheit_nr, lage, typ, wohnflaeche_qm, zimmer, miteigentumsanteil) VALUES ("
            + ", ".join(
                [
                    esc(u["id"]),
                    esc(u["haus_id"]),
                    esc(u.get("einheit_nr")),
                    esc(u.get("lage")),
                    esc(u.get("typ")),
                    num(u.get("wohnflaeche_qm")),
                    num(u.get("zimmer")),
                    num(u.get("miteigentumsanteil")),
                ]
            )
            + ");"
        )
    push("")

    # owners + owner_units
    for o in eigentuemer:
        push(
            "INSERT INTO owners (id, property_id, anrede, vorname, nachname, firma, strasse, plz, ort, land, email, telefon, iban, bic, selbstnutzer, sev_mandat, beirat, sprache) VALUES ("
            + ", ".join(
                [
                    esc(o["id"]),
                    esc(PROPERTY_ID),
                    esc(o.get("anrede")),
                    esc(o.get("vorname")),
                    esc(o.get("nachname")),
                    esc(o.get("firma")),
                    esc(o.get("strasse")),
                    esc(o.get("plz")),
                    esc(o.get("ort")),
                    esc(o.get("land")),
                    esc(o.get("email")),
                    esc(o.get("telefon")),
                    esc(o.get("iban")),
                    esc(o.get("bic")),
                    boolint(o.get("selbstnutzer")),
                    boolint(o.get("sev_mandat")),
                    boolint(o.get("beirat")),
                    esc(o.get("sprache")),
                ]
            )
            + ");"
        )
        unit_ids = [s.strip() for s in (o.get("einheit_ids") or "").split(";") if s.strip()]
        for uid in unit_ids:
            push(
                f"INSERT INTO owner_units (owner_id, unit_id) VALUES ({esc(o['id'])}, {esc(uid)});"
            )
    push("")

    # tenants
    for m in mieter:
        push(
            "INSERT INTO tenants (id, property_id, anrede, vorname, nachname, email, telefon, einheit_id, eigentuemer_id, mietbeginn, mietende, kaltmiete, nk_vorauszahlung, kaution, iban, bic, sprache) VALUES ("
            + ", ".join(
                [
                    esc(m["id"]),
                    esc(PROPERTY_ID),
                    esc(m.get("anrede")),
                    esc(m.get("vorname")),
                    esc(m.get("nachname")),
                    esc(m.get("email")),
                    esc(m.get("telefon")),
                    esc(m.get("einheit_id")),
                    esc(m.get("eigentuemer_id")),
                    esc(m.get("mietbeginn")),
                    esc(m.get("mietende")),
                    num(m.get("kaltmiete")),
                    num(m.get("nk_vorauszahlung")),
                    num(m.get("kaution")),
                    esc(m.get("iban")),
                    esc(m.get("bic")),
                    esc(m.get("sprache")),
                ]
            )
            + ");"
        )
    push("")

    # service providers, scoped to the demo property
    for d in dienstleister:
        push(
            "INSERT INTO service_providers (id, property_id, firma, branche, ansprechpartner, email, telefon, strasse, plz, ort, land, iban, bic, ust_id, steuernummer, stil, sprache, vertrag_monatlich, stundensatz) VALUES ("
            + ", ".join(
                [
                    esc(d["id"]),
                    esc(PROPERTY_ID),
                    esc(d.get("firma")),
                    esc(d.get("branche")),
                    esc(d.get("ansprechpartner")),
                    esc(d.get("email")),
                    esc(d.get("telefon")),
                    esc(d.get("strasse")),
                    esc(d.get("plz")),
                    esc(d.get("ort")),
                    esc(d.get("land")),
                    esc(d.get("iban")),
                    esc(d.get("bic")),
                    esc(d.get("ust_id")),
                    esc(d.get("steuernummer")),
                    esc(d.get("stil")),
                    esc(d.get("sprache")),
                    num(d.get("vertrag_monatlich")),
                    num(d.get("stundensatz")),
                ]
            )
            + ");"
        )
    push("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(lines)} statements)")
    print(
        f"counts: properties=1 buildings={len(buildings)} units={len(einheiten)} "
        f"owners={len(eigentuemer)} tenants={len(mieter)} providers={len(dienstleister)}"
    )


if __name__ == "__main__":
    main()
